name: How to use a Windows Runner on GitHub Actions
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get dir
        shell: pwsh
        run: |
          dir
